version: '3.8'
services:
  api:
    build: .
    command: pnpm run dev
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      WEATHERSTACK_API_KEY: ${WEATHERSTACK_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - test-db

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_management_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
