version: '3.8'
services:
  api:
    build: .
    command: pnpm run dev
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/property_management
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
