name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: property_management_test
  TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5433/property_management_test
  NODE_ENV: test
  WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: |
          pnpm prisma:generate

      - name: Run migrations
        run: pnpm db:migrate:test

      - name: Type Check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: |
          pnpm test
